### ISSUE TITLE
mention it's not related with healthchecks.io

### ISSUE THREAD

**Issue by smknstd** [renoki-co/laravel-healthchecks#4]
Maybe you could mention somewhere that this library is not related with https://healthchecks.io/

**Comment by rennokki** [comment]
I'm not sure if I should mention it since the description of the package clearly shows off the purpose. 🤷

**Comment by smknstd** [comment]
I might not be familiar with the concept and after reading the description (and even the complete readme), the purpose was still not 100% clear to me. Maybe you could better define what is a "healthchecks" and give an example on how it used.
