### ISSUE TITLE
Publish version 1.2.0 to packagist

### ISSUE THREAD

**Issue by ramirovarandas** [renoki-co/laravel-healthchecks#5]
Hi, first of all thanks for this project, it's really helpful!

After the release of Laravel 8 and trying to upgrade, we've checked the tags and there's a 1.2.0 version, however when running `composer update` it says it can't find this version.

It's probably just a packagist release that's needed.

Thanks!

**Comment by rennokki** [comment]
Sorry for the issues, it seems like packagist told me it's not auto-updating. `1.2.0` is available now :D
